import numpy as np
from epistem import EpistemEngine, generate_report

def main():
    # Real options: Candidate descriptions
    options = [
        "Experienced backend engineer, 10 years experience, specializes in high-scale distributed systems and Python performance.",
        "Talented junior dev, recent bootcamp grad, extremely high potential, very eager to learn, strong culture fit, low salary requirement.",
        "Solid mid-level fullstack developer, reliable, good communicator, experience with React and Node, moderate salary.",
        "Academic researcher, PhD in AI, very deep theoretical knowledge, limited industry experience, high salary requirement."
    ]
    option_names = ["Senior Backend", "Junior Rising Star", "Reliable Fullstack", "AI Researcher"]

    # Evaluators (Parties) with different priorities over the extracted dimensions.
    # Note: Dimension labels will be generated by the ProfileBuilder.
    # We'll use 4 parties and 4 dimensions for this example.
    # Dimensions are derived from the text, so we map party weights to the dimension count.

    # Party 1: Engineering Manager (Prioritizes experience and backend depth)
    # Party 2: Product Lead (Prioritizes fullstack versatility and speed)
    # Party 3: CFO (Prioritizes cost-effectiveness)
    # Party 4: CTO (Prioritizes R&D and future-proofing)

    # We will let the engine derive the dimensions first, but we need to provide weights.
    # For this demo, we'll assume a 4-dimensional profile space.
    party_weights = np.array([
        [0.8, 0.2, 0.0, 0.5], # EM
        [0.3, 0.7, 0.2, 0.1], # PL
        [0.1, 0.1, 0.9, 0.0], # CFO
        [0.5, 0.0, 0.1, 0.9]  # CTO
    ])

    # Normalize party weights so each party's weights sum to 1
    party_weights = party_weights / party_weights.sum(axis=1)[:, None]

    print("--- Running Epistem Hiring Committee Consensus ---")
    engine = EpistemEngine(option_names, options, party_weights)
    result = engine.run()

    generate_report(result)

if __name__ == "__main__":
    main()
